######################################################################
# Automatically generated by qmake (2.00a) Sat Apr 29 17:02:33 2006
######################################################################

TEMPLATE = subdirs

# Directories
SUBDIRS += ibpp src 
CONFIG += warn_on

