# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./libquirkflow
# Target is a library:  ../bin/libquirkflow

MOC_DIR = ../obj 
UI_DIR = ../obj 
OBJECTS_DIR = ../obj 
TARGET = ../bin/libquirkflow 
CONFIG += release \
          warn_on \
          dll 
TEMPLATE = lib 
SOURCES += libquirkflow.cpp 
