#
#
#  C++ Portable Types Library (PTypes)
#  Version 2.1.0  Released 15-May-2007
#
#  Copyright (C) 2001-2007 Hovik Melikyan
#
#  http://www.melikyan.com/ptypes/
#
#
#
# Makefile for CYGWIN, called from ../Makefile
#

CXX = g++

LIBTOOL = $(CXX) -shared
SOSTRIP = strip

SOEXT = so
SOREALNAME = $(SOBASENAME).$(SOEXT).$(SOVER)
SOINSTOPT = -Xlinker -soname -Xlinker
SOINSTNAME = $(SOREALNAME)

PREFIX = /usr

include Makefile.common

