#
#
#  C++ Portable Types Library (PTypes)
#  Version 2.1.0  Released 15-May-2007
#
#  Copyright (C) 2001-2007 Hovik Melikyan
#
#  http://www.melikyan.com/ptypes/
#
#
#
# Makefile for FreeBSD, called from ../Makefile
#

CXX = g++

OS_CXXOPTS = -pthread
OS_LDLIBS = -lc_r

include Makefile.common

